### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by mxmilkiib** [BN701/Multi-Arp#1]
Some advice would be welcome, thanks :)

**Comment by BN701** [comment]
Ah ... just found your comment. I didn't think anyone was watching :) I've been using this repository for backup up to now. I'll see if I can write some notes some time soon. Meanwhile, I don't know whether you've looked at the readme and other files, but I've been having a go at getting things documented, This should give you a better idea of whether you'd want to try building at the moment.

B

**Comment by BN701** [comment]
I've hacked together a makefile and there some instructions for building in **Doc/build_me.md**. You can be the first to have a go. Do let me know how you get on :)

(And apologies if I've not been following Linux build/install conventions. I'm an old time Windows hacker who's not done any serious development in nearly ten years and I've only really been getting to know Linux for the last year or so.)

B

**Comment by mxmilkiib** [comment]
Thank you, got it built (Arch Linux). This is how it looks on running:
![silver_2018-01-06-02 48 32](https://user-images.githubusercontent.com/108225/34635773-1c55470c-f28c-11e7-8b41-5c94a8a7ef4f.png)
